import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BootstrapBundleJS from "./BootstrapBundleJS";
import AppHeader from "./AppHeader";
import AppMenu from "./AppMenu";
import AppContextProvider from "./states/context/AppContextProvider";
import StoreProvider from "./states/redux/StoreProvider";
import LoadAccessToken from "./apis/LoadAccessToken";
import { useContext } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BootstrapBundleJS />
        {/* Ch07: Redux */}
        <StoreProvider>
          <AppContextProvider>
            <LoadAccessToken />
            <div className="d-flex flex-column vh-100">
              <AppHeader />
              <div className="flex-grow-1 container-fluid">
                <div className="row">
                  <div className="col-md-4 col-lg-3 p-2">
                    <AppMenu />
                  </div>
                  <div className="col-md-8 col-lg-9 p-2">
                    {children}
                  </div>
                </div>
              </div>
            </div>
          </AppContextProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
